// Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

// News
export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_CREATE_REQUEST = "NEWS_CREATE_REQUEST";
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL";
export const NEWS_CREATE_RESET = "NEWS_CREATE_RESET";

export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST";
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";

export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";
export const NEWS_UPDATE_RESET = "NEWS_UPDATE_RESET";

// Single News
export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS_REQUEST";
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS_SUCCESS";
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS_FAIL";
export const NEWS_DETAILS_RESET = "NEWS_DETAILS_RESET";

// Latest News
export const LATEST_NEWS_REQUEST = "LATEST_NEWS_REQUEST";
export const LATEST_NEWS_SUCCESS = "LATEST_NEWS_SUCCESS";
export const LATEST_NEWS_FAIL = "LATEST_NEWS_FAIL";

// Events
export const UPCOMING_EVENTS_REQUEST = "UPCOMING_EVENTS_REQUEST";
export const UPCOMING_EVENTS_SUCCESS = "UPCOMING_EVENTS_SUCCESS";
export const UPCOMING_EVENTS_FAIL = "UPCOMING_EVENTS_FAIL";

export const ALL_ADMIN_EVENTS_REQUEST = "ALL_ADMIN_EVENTS_REQUEST";
export const ALL_ADMIN_EVENTS_SUCCESS = "ALL_ADMIN_EVENTS_SUCCESS";
export const ALL_ADMIN_EVENTS_FAIL = "ALL_ADMIN_EVENTS_FAIL";

export const EVENTS_CREATE_REQUEST = "EVENTS_CREATE_REQUEST";
export const EVENTS_CREATE_SUCCESS = "EVENTS_CREATE_SUCCESS";
export const EVENTS_CREATE_FAIL = "EVENTS_CREATE_FAIL";
export const EVENTS_CREATE_RESET = "EVENTS_CREATE_RESET";

export const EVENTS_DELETE_REQUEST = "EVENTS_DELETE_REQUEST";
export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS";
export const EVENTS_DELETE_FAIL = "EVENTS_DELETE_FAIL";

export const UPCOMING_LATEST_EVENTS_REQUEST = "UPCOMING_LATEST_EVENTS_REQUEST";
export const UPCOMING_LATEST_EVENTS_SUCCESS = "UPCOMING_LATEST_EVENTS_SUCCESS";
export const UPCOMING_LATEST_EVENTS_FAIL = "UPCOMING_LATEST_EVENTS_FAIL";

// Gallery
export const GALLERY_ALBUMS_REQUEST = "GALLERY_ALBUMS_REQUEST";
export const GALLERY_ALBUMS_SUCCESS = "GALLERY_ALBUMS_SUCCESS";
export const GALLERY_ALBUMS_FAIL = "GALLERY_ALBUMS_FAIL";

export const GALLERY_ALBUM_CREATE_REQUEST = "GALLERY_ALBUM_CREATE_REQUEST";
export const GALLERY_ALBUM_CREATE_SUCCESS = "GALLERY_ALBUM_CREATE_SUCCESS";
export const GALLERY_ALBUM_CREATE_FAIL = "GALLERY_ALBUM_CREATE_FAIL";
export const GALLERY_ALBUM_CREATE_RESET = "GALLERY_ALBUM_CREATE_RESET";

export const GALLERY_ALBUM_DELETE_REQUEST = "GALLERY_ALBUM_DELETE_REQUEST";
export const GALLERY_ALBUM_DELETE_SUCCESS = "GALLERY_ALBUM_DELETE_SUCCESS";
export const GALLERY_ALBUM_DELETE_FAIL = "GALLERY_ALBUM_DELETE_FAIL";

export const SINGLE_ALBUM_REQUEST = "SINGLE_ALBUM_REQUEST";
export const SINGLE_ALBUM_SUCCESS = "SINGLE_ALBUM_SUCCESS";
export const SINGLE_ALBUM_FAIL = "SINGLE_ALBUM_FAIL";

// Gallery Videos
export const GALLERY_VIDEOS_REQUEST = "GALLERY_VIDEOS_REQUEST";
export const GALLERY_VIDEOS_SUCCESS = "GALLERY_VIDEOS_SUCCESS";
export const GALLERY_VIDEOS_FAIL = "GALLERY_VIDEOS_FAIL";

export const GALLERY_VIDEOS_ADD_REQUEST = "GALLERY_VIDEOS_ADD_REQUEST";
export const GALLERY_VIDEOS_ADD_SUCCESS = "GALLERY_VIDEOS_ADD_SUCCESS";
export const GALLERY_VIDEOS_ADD_FAIL = "GALLERY_VIDEOS_ADD_FAIL";
export const GALLERY_VIDEOS_ADD_RESET = "GALLERY_VIDEOS_ADD_RESET";

export const GALLERY_VIDEOS_DELETE_REQUEST = "GALLERY_VIDEOS_DELETE_REQUEST";
export const GALLERY_VIDEOS_DELETE_SUCCESS = "GALLERY_VIDEOS_DELETE_SUCCESS";
export const GALLERY_VIDEOS_DELETE_FAIL = "GALLERY_VIDEOS_DELETE_FAIL";

// Admin Settings
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";
export const DARK_MODE = "DARK_MODE";
export const ADMIN_MODE = "ADMIN_MODE";

// Staffs
export const AVAILABLE_STAFFS_REQUEST = "AVAILABLE_STAFFS_REQUEST";
export const AVAILABLE_STAFFS_SUCCESS = "AVAILABLE_STAFFS_SUCCESS";
export const AVAILABLE_STAFFS_FAIL = "AVAILABLE_STAFFS_FAIL";

export const STAFFS_CREATE_REQUEST = "STAFFS_CREATE_REQUEST";
export const STAFFS_CREATE_SUCCESS = "STAFFS_CREATE_SUCCESS";
export const STAFFS_CREATE_FAIL = "STAFFS_CREATE_FAIL";
export const STAFFS_CREATE_RESET = "STAFFS_CREATE_RESET";

export const STAFFS_DELETE_REQUEST = "STAFFS_DELETE_REQUEST";
export const STAFFS_DELETE_SUCCESS = "STAFFS_DELETE_SUCCESS";
export const STAFFS_DELETE_FAIL = "STAFFS_DELETE_FAIL";

// Notices
export const AVAILABLE_NOTICES_REQUEST = "AVAILABLE_NOTICES_REQUEST";
export const AVAILABLE_NOTICES_SUCCESS = "AVAILABLE_NOTICES_SUCCESS";
export const AVAILABLE_NOTICES_FAIL = "AVAILABLE_NOTICES_FAIL";

export const NOTICES_CREATE_REQUEST = "NOTICES_CREATE_REQUEST";
export const NOTICES_CREATE_SUCCESS = "NOTICES_CREATE_SUCCESS";
export const NOTICES_CREATE_FAIL = "NOTICES_CREATE_FAIL";
export const NOTICES_CREATE_RESET = "NOTICES_CREATE_RESET";

export const NOTICES_DELETE_REQUEST = "NOTICES_DELETE_REQUEST";
export const NOTICES_DELETE_SUCCESS = "NOTICES_DELETE_SUCCESS";
export const NOTICES_DELETE_FAIL = "NOTICES_DELETE_FAIL";

export const LATEST_NOTICES_REQUEST = "LATEST_NOTICES_REQUEST";
export const LATEST_NOTICES_SUCCESS = "LATEST_NOTICES_SUCCESS";
export const LATEST_NOTICES_FAIL = "LATEST_NOTICES_FAIL";

// Downloads
export const FILE_DOWNLOAD_REQUEST = "FILE_DOWNLOAD_REQUEST";
export const FILE_DOWNLOAD_SUCCESS = "FILE_DOWNLOAD_SUCCESS";
export const FILE_DOWNLOAD_FAIL = "FILE_DOWNLOAD_FAIL";
export const FILE_DOWNLOAD_RESET = "FILE_DOWNLOAD_RESET";

export const FILE_CREATE_REQUEST = "FILE_CREATE_REQUEST";
export const FILE_CREATE_SUCCESS = "FILE_CREATE_SUCCESS";
export const FILE_CREATE_FAIL = "FILE_CREATE_FAIL";
export const FILE_CREATE_RESET = "FILE_CREATE_RESET";

export const FILE_DELETE_REQUEST = "FILE_DELETE_REQUEST";
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS";
export const FILE_DELETE_FAIL = "FILE_DELETE_FAIL";

export const SINGLE_FILE_CREATE_REQUEST = "SINGLE_FILE_CREATE_REQUEST";
export const SINGLE_FILE_CREATE_SUCCESS = "SINGLE_FILE_CREATE_SUCCESS";
export const SINGLE_FILE_CREATE_FAIL = "SINGLE_FILE_CREATE_FAIL";

// Carousel
export const AVAILABLE_CAROUSEL_REQUEST = "AVAILABLE_CAROUSEL_REQUEST";
export const AVAILABLE_CAROUSEL_SUCCESS = "AVAILABLE_CAROUSEL_SUCCESS";
export const AVAILABLE_CAROUSEL_FAIL = "AVAILABLE_CAROUSEL_FAIL";

export const CAROUSEL_CREATE_REQUEST = "CAROUSEL_CREATE_REQUEST";
export const CAROUSEL_CREATE_SUCCESS = "CAROUSEL_CREATE_SUCCESS";
export const CAROUSEL_CREATE_FAIL = "CAROUSEL_CREATE_FAIL";
export const CAROUSEL_CREATE_RESET = "CAROUSEL_CREATE_RESET";

export const CAROUSEL_DELETE_REQUEST = "CAROUSEL_DELETE_REQUEST";
export const CAROUSEL_DELETE_SUCCESS = "CAROUSEL_DELETE_SUCCESS";
export const CAROUSEL_DELETE_FAIL = "CAROUSEL_DELETE_FAIL";

// Registration
export const SUBMITTED_REGISTRATION_REQUEST = "SUBMITTED_REGISTRATION_REQUEST";
export const SUBMITTED_REGISTRATION_SUCCESS = "SUBMITTED_REGISTRATION_SUCCESS";
export const SUBMITTED_REGISTRATION_FAIL = "SUBMITTED_REGISTRATION_FAIL";

export const REGISTRATION_CREATE_REQUEST = "REGISTRATION_CREATE_REQUEST";
export const REGISTRATION_CREATE_SUCCESS = "REGISTRATION_CREATE_SUCCESS";
export const REGISTRATION_CREATE_FAIL = "REGISTRATION_CREATE_FAIL";

// Modal
export const ADDED_MODAL_REQUEST = "ADDED_MODAL_REQUEST";
export const ADDED_MODAL_SUCCESS = "ADDED_MODAL_SUCCESS";
export const ADDED_MODAL_FAIL = "ADDED_MODAL_FAIL";

export const MODAL_CREATE_REQUEST = "MODAL_CREATE_REQUEST";
export const MODAL_CREATE_SUCCESS = "MODAL_CREATE_SUCCESS";
export const MODAL_CREATE_FAIL = "MODAL_CREATE_FAIL";
export const MODAL_CREATE_RESET = "MODAL_CREATE_RESET";

export const MODAL_DELETE_REQUEST = "MODAL_DELETE_REQUEST";
export const MODAL_DELETE_SUCCESS = "MODAL_DELETE_SUCCESS";
export const MODAL_DELETE_FAIL = "MODAL_DELETE_FAIL";
